links = [
    "https://web.facebook.com/media/set/?set=a.800620883292401&type=3",
    "https://web.facebook.com/media/set/?set=a.836741799680309&type=3",
    "https://web.facebook.com/media/set/?set=a.946077205413434&type=3",
    "https://web.facebook.com/media/set/?set=a.1587975287890286&type=3",
    "https://web.facebook.com/media/set/?set=a.1222583421096143&type=3",
    "https://web.facebook.com/media/set/?set=a.1210647198956432&type=3",
    "https://web.facebook.com/media/set/?set=a.1171262362894916&type=3",
    "https://web.facebook.com/photo.php?fbid=1019254761450731&id=547623881947157&set=a.547625708613641&_rdc=1&_rdr#",
    "https://palungjit.org/threads/20-%E0%B8%A1%E0%B8%B5%E0%B8%84-59-%E0%B8%87%E0%B8%B2%E0%B8%99%E0%B9%81%E0%B8%AA%E0%B8%94%E0%B8%87%E0%B8%98%E0%B8%A3%E0%B8%A3%E0%B8%A1-%E0%B8%9B%E0%B8%8F%E0%B8%B4%E0%B8%9A%E0%B8%B1%E0%B8%95%E0%B8%B4%E0%B8%98%E0%B8%A3%E0%B8%A3%E0%B8%A1-%E0%B9%82%E0%B8%94%E0%B8%A2%E0%B8%8A%E0%B8%A1%E0%B8%A3%E0%B8%A1%E0%B8%81%E0%B8%B1%E0%B8%A5%E0%B8%A2%E0%B8%B2%E0%B8%93%E0%B8%98%E0%B8%A3%E0%B8%A3%E0%B8%A1-%E0%B8%84%E0%B8%A3%E0%B8%B1%E0%B9%89%E0%B8%87%E0%B8%97%E0%B8%B5%E0%B9%88-32-%E0%B8%A1%E0%B8%AB%E0%B8%B2%E0%B8%A7%E0%B8%B4%E0%B8%97%E0%B8%A2%E0%B8%B2%E0%B8%A5%E0%B8%B1%E0%B8%A2%E0%B9%80%E0%B8%97%E0%B8%84%E0%B9%82%E0%B8%99%E0%B9%82%E0%B8%A5%E0%B8%A2%E0%B8%B5%E0%B8%A3%E0%B8%B2%E0%B8%8A%E0%B8%A1%E0%B8%87%E0%B8%84%E0%B8%A5%E0%B8%81%E0%B8%A3%E0%B8%B8%E0%B8%87%E0%B9%80%E0%B8%97%E0%B8%9E.562698/",
    
    
]